version: '3'

services:

  workspace:
    build:
      context: ${DOCKER_PATH}/workspace
      args:
        - PHP_DOCKERFILE_SOURCE=${PHP_DOCKERFILE_SOURCE}
    volumes:
      - ${APP_PATH}:/var/www
    tty: true
    networks:
      - network

  s3-api:
    build:
      context: ${DOCKER_PATH}/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${PHP_UPSTREAM_PORT}
    volumes:
      - ${APP_PATH}/docker/devops/sites:/etc/nginx/sites-available
      - ./nginx/ssl/:/etc/nginx/ssl
      - ${APP_PATH}:/var/www
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    links:
      - php-fpm
    networks:
      - network

  php-fpm:
    build:
      context: ${DOCKER_PATH}/php-fpm
      args:
        - PHP_FPM_DOCKERFILE_SOURCE=${PHP_FPM_DOCKERFILE_SOURCE}
        - PHP_UPSTREAM_PORT=${PHP_UPSTREAM_PORT}
    volumes:
      - ${APP_PATH}:/var/www
    expose:
      - ${PHP_UPSTREAM_PORT}
    networks:
      - network

  minio:
    build:
      context: ${DOCKER_PATH}/minio
      args:
        - MINIO_DOCKERFILE_SOURCE=${MINIO_DOCKERFILE_SOURCE}
    ports:
      - 9000:9000
    volumes:
      - ${DATA_PATH_HOST}/mino/data:/export
      - ${DATA_PATH_HOST}/minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    networks:
      - network

volumes:
  minio:
    driver: local

networks:
  network:
    driver: ${NETWORKS_DRIVER}
